### ISSUE TITLE
thead + xml:id is allowed

### ISSUE THREAD

**Issue by sknorr** [openSUSE/geekodoc#52] opened 2018-04-25 09:20 UTC
## Problem Description

```
<thead xml:id="...">
```

This is valid

## Expected Behaviour

It shouldn't be valid -- there is no reason to xref a thead (well, barring transclusions) and there is no way to generate a title from one. Also creates issues with Novdoc conversion currently.

**Comment by tomschr** [comment] 2018-04-27 07:08
Duplicate of #55

**Closed by tomschr** 2018-04-27 07:08 UTC
Labels: duplicate
